#pragma once
#ifdef OS_IS_WINDOWS
	#define RHI_USE_PLATFORM_WIN32_KHR	1
#endif
#ifdef OS_IS_ANDROID
	#define RHI_USE_PLATFORM_ANDROID_KHR		0
#endif
#ifdef OS_IS_LINUX
	#define RHI_USE_PLATFORM_WAYLAND_KHR	0
	#define RHI_USE_PLATFORM_XCB_KHR		1
	#define RHI_USE_PLATFORM_XLIB_KHR		0
#endif
