set (USE_VULKAN     false)
set (USE_GLFW       true)
set (USE_QT         false)
set (USE_BOOST      true)
set (USE_PORTAUDIO  false)
set (USE_SFML       true)
set (USE_MFC        false)
set (USE_MP3LAME    true)
set (USE_D3D12  	true)
set (USE_GLM  	true)
# glfw need x11 on linux
if (CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set (USE_X11    true)
else ()
    set (USE_X11    false)
endif ()

if (CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set (USE_ALSA    true)
else ()
    set (USE_ALSA    false)
endif ()
    set (USE_ALSA    false)

if (CMAKE_SYSTEM_NAME STREQUAL "Window")
	set (USE_D3D12  true)
    set (USE_MFC    true)
else ()
	set (USE_D3D12  false)
    set (USE_MFC    false)
endif ()
set (USE_MODBUS     false)
set (USE_IrrKlang   false)
set (USE_FLTK       false)
set (USE_wxWidget   false)
set (USE_CEGUI      false)
set (USE_MYGUI      false)
set (USE_LVGL       false)
set (USE_NANA       false)
set (USE_MQTT       false)
set (USE_ASSIMP     false)
set (USE_CEF        false)
set (USE_SDL3       false)
set (USE_FDKAAC     false)
set (USE_OPUS       false)
set (USE_OGG        false)
set (USE_TWOLAME    false)
set (USE_VORBIS     false)
set (USE_FLAC       false)
set (USE_WEBP       false)
set (USE_GIF        false)
set (USE_OPENEXR    false)
set (USE_IMATH      false)
set (USE_STB        false)
set (USE_BOOST      false)
set (USE_CURL       false)
set (USE_OPENSSL    false)
set (USE_DXFRW      false)
set (USE_CEF        false)
set (USE_SDL3       false)




