set (USE_VULKAN     true)
set (USE_GLFW       true)
set (USE_QT         true)
set (USE_BOOST      true)
set (USE_SFML       true)
set (USE_MP3LAME    true)
set (USE_D3D12  	true)
set (USE_GLM  	    true)
set (USE_FFMPEG     true)
set (USE_OpenAL     true)
set (USE_OGG        true)
set (USE_FLAC       true)
set (USE_LC3        true)
set (USE_VORBIS     true)
set (USE_FDKAAC     true)
set (USE_TWOLAME    true)
set (USE_MQTT       true)
set (USE_MODBUS     true)
set (USE_LIVE555    true)
# live555 need openssl
set (USE_OPENSSL    true)
set (USE_STB        true)
set (USE_MFC        false)
set (USE_PORTAUDIO  false)
set (USE_CEF        false)
set (USE_SDL3       false)
set (USE_embroidery false)
set (USE_LVGL       false)
# glfw need x11 on linux
if (CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set (USE_Xlib   true)
    set (USE_XCB    true)
    set (USE_BLUEZ  false)
    set (USE_ALSA    true)
else ()
    set (USE_Xlib   false)
    set (USE_XCB    false)
    set (USE_BLUEZ  false)
    set (USE_ALSA    false)
endif ()

if (CMAKE_SYSTEM_NAME STREQUAL "Window")
	set (USE_D3D12  true)
    set (USE_MFC    true)
else ()
	set (USE_D3D12  false)
    set (USE_MFC    false)
endif ()
set (USE_IrrKlang   false)
set (USE_FLTK       false)
set (USE_wxWidget   false)
set (USE_CEGUI      false)
set (USE_MYGUI      false)
set (USE_NANA       false)
set (USE_ASSIMP     false)
set (USE_OPUS       false)
set (USE_WEBP       false)
set (USE_GIF        false)
set (USE_OPENEXR    false)
set (USE_IMATH      false)
set (USE_BOOST      false)
set (USE_CURL       false)
set (USE_DXFRW      false)





