#pragma once

/*
*   VK_IMAGE_LAYOUT_UNDEFINED
*   VK_IMAGE_LAYOUT_GENERAL
*   VK_IMAGE_LAYOUT_PREINITIALIZED
*   VK_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL
*   VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL
*       VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT
*   VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL
*   VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL
*   VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL
*   VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL
*   VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL
*       等价于 VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL and VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL.
*   VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL
*       等价于 VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL and VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL.
*   VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL
*       等价于 VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL and VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL.
*   VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL
*       等价于 VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL and VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL.
*   VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL
*       VK_IMAGE_USAGE_SAMPLED_BIT or VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT
*   VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL
*   VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMA
*   VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL
 */