#pragma once

/*
 *   VK_IMAGE_USAGE_TRANSFER_SRC_BIT
 *   VK_IMAGE_USAGE_TRANSFER_DST_BIT
 *   VK_IMAGE_USAGE_SAMPLED_BIT
 *   VK_IMAGE_USAGE_STORAGE_BIT
 *   VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT
 *   VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT
 *   VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT
 *   VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT
 *   VK_IMAGE_USAGE_HOST_TRANSFER_BIT
 */

/*
 * VkImageMemoryBarrier2与VkImageCreateInfo::usage限制
 * 如果oldLayout 或者 newLayout是                                 那么VkImageCreateInfo::usage必须是
 * VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL                         VK_IMAGE_USAGE_TRANSFER_SRC_BIT
 * VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL                         VK_IMAGE_USAGE_TRANSFER_DST_BIT
 * VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL                     VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT
 * VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL             VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT
 * VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL              VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT
 * VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL   VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT
 * VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL   VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT
 * VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL                     VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT
 * VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL                   VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT
 * VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL                     VK_IMAGE_USAGE_SAMPLED_BIT
 *                                                              VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT
 * VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL                      VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT
 *                                                              VK_IMAGE_USAGE_SAMPLED_BIT
 *                                                              VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT
 * VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL                    VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT
 *                                                              VK_IMAGE_USAGE_SAMPLED_BIT
 *                                                              VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT
 *
 *
 *
 *
 *
 *
 *
 */